homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

site:
    resource: SiteBundle/Resources/config/routing.yml

user:
    resource: UserBundle/Resources/config/routing.yml
